vulkan: enable VK_ENABLE_BETA_EXTENSIONS
Fixes build failures caused by missing NV CUDA.
error: 'vkCreateCudaModuleNV' undeclared here (not in a function); did you mean 'vkCreateCuModuleNVX'?